### PR TITLE
Keys.plist

### LINKED ISSUE #6: Remove API key from codebase
Read from a file/dictionary/etc which is not tracked?

### PR DESCRIPTION
**Pull request by aaronschachter**
Fixes #6

Adds a new untracked plist file to store data like API keys, which is populated with dummy data.  Gets us in a good place to start on #3 as well.

### CODE REVIEW

**Comment by jonuy** [comment]
Onus is on each dev to supply their own keys.plist in order to build the project. I kinda like the idea of submitting a keys.plist file with dummy values so at least the dev knows what keys need to be filled out.

Either way, whatever direction you go in :+1:

**Comment by aaronschachter** [comment]
Hmm, I suppose we could commit an empty keys.plist into the repo.. and then add it into `.gitignore` once it exists in the repo?

**Comment by jonuy** [comment]
I think you can still include it in this PR if you want by just force committing the dummy keys.plist

**Comment by aaronschachter** [comment]
@jonuy Updated, now including a dummy `keys.plist`

**Comment by jonuy** [comment]
:+1:

**Comment by aaronschachter** [comment]
Making changes to `keys.plist` still shows up as tracked :(

Per http://stackoverflow.com/questions/7072213/how-to-stop-tracking-a-file-without-removing-it-from-repo, there is a suggestion to create a dummy file .. there's also an answer to use `git update-index --assume-unchanged <file>` locally, but the index will be cleared upon a `git reset --hard` ...

**Pull request merged**
